FROM alpine:latest
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install --no-cache dkpro-cassis
ADD main.py main.py
ADD communication_xmi.lua communication.lua
ADD dkpro-core-types.xml dkpro-core-types.xml
CMD python3 main.py
