FROM alpine:latest
ENV PYTHONUNBUFFERED=1
RUN apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
RUN python3 -m ensurepip
RUN pip3 install --no-cache --upgrade pip setuptools
RUN pip3 install fastapi
RUN pip3 install pydantic
RUN pip3 install uvicorn[standard]
ADD monitor.py monitor.py
ADD index.html index.html
# ENTRYPOINT ["uvicorn" "monitor:app" "--host" "localhost" "--port" "8086"]
ENTRYPOINT uvicorn monitor:app --host "0.0.0.0" --port 8086
